name: image_app
description: Weather App built with Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  dio: ^5.4.0
  intl: ^0.19.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  # firebase_core: ^3.0.0
  # firebase_auth: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
